Repository matrix-org/matrix-authentication-service, pull requests merged in 2023-11, with the labels that each got.

#2034 syn2mas: accept ULIDs and UUIDs in arguments for upstream IDP mapping
  tools/syn2mas/src/migrate.mts
Labels: T-Enhancement, A-Migration

#2035 Better release workflow
  .github/workflows/release.yaml
  Cargo.toml
Labels: T-Task, A-CI

#2048 syn2mas: support for deactivated users & use timestamps when generating IDs
  tools/syn2mas/src/advisor.mts
  tools/syn2mas/src/migrate.mts
Labels: A-Migration

#2051 Fix the login template not rendering on policy error
  crates/templates/src/context.rs
  templates/components/field.html
  templates/pages/sso.html
  translations/en.json
Labels: T-Defect, A-Login-Flow, A-Templates

#2075 Use minijinja templates to map OIDC claims to user attributes
  Cargo.lock
  crates/cli/src/commands/config.rs
  crates/config/src/sections/upstream_oauth2.rs
  crates/data-model/src/lib.rs
  crates/data-model/src/upstream_oauth2/mod.rs
  crates/data-model/src/upstream_oauth2/provider.rs
  crates/handlers/Cargo.toml
  crates/handlers/src/upstream_oauth2/callback.rs
  crates/handlers/src/upstream_oauth2/link.rs
  docs/config.schema.json
Labels: T-Enhancement, A-Upstream-OAuth

#2100 dockerfile: bump rust, opa, nodejs and debian version
  .github/workflows/build.yaml
  .github/workflows/ci.yaml
  .github/workflows/coverage.yaml
  Dockerfile
  policies/Makefile
Labels: T-Task, A-Container

#2102 Try to fix a flakey frontend test
  frontend/src/components/Layout/Layout.test.tsx
Labels: A-Frontend, T-Task

#2107 dependabot: Include the opentelemetry_sdk crate in the opentelemetry group
  .github/dependabot.yml
Labels: T-Task, A-CI

#2127 Add upstream OAuth 2.0 providers name and branding
  crates/cli/src/commands/config.rs
  crates/config/src/sections/upstream_oauth2.rs
  crates/data-model/src/upstream_oauth2/provider.rs
  crates/handlers/src/upstream_oauth2/cache.rs
  crates/handlers/src/upstream_oauth2/link.rs
  crates/handlers/src/views/login.rs
  crates/storage-pg/.sqlx/query-1f131aa966a4358d83e7247d3e30451f8bcf5df20faf46a4a4c0d4a36d1ff173.json
  crates/storage-pg/.sqlx/query-2098ff49e9f4b847543b3186dbc4a8cdf1d21f788a533477c233455c57a1b755.json
  crates/storage-pg/.sqlx/query-311957a0b745660aa2a21b1bd211376739318efa1e84670e04189e1257d4a8ed.json
  crates/storage-pg/.sqlx/query-4668abf6520ecca2fa71a26b02d206600624bbba57985d4a7fba2763478cd065.json
  crates/storage-pg/.sqlx/query-75b58c1b7f4e26997e961ad64418938938f09b3215a9b14f7edb3dd91cdf2dd5.json
  crates/storage-pg/.sqlx/query-eb5af2b52b65eb9fba94418075dac0ddb04752d374e1905d1d935313090375c9.json
  crates/storage-pg/migrations/20231120110559_upstream_oauth_branding.sql
  crates/storage-pg/src/iden.rs
  crates/storage-pg/src/upstream_oauth2/mod.rs
  crates/storage-pg/src/upstream_oauth2/provider.rs
  crates/storage/src/upstream_oauth2/provider.rs
  docs/config.schema.json
  templates/components/idp_brand.html
  templates/pages/login.html
  translations/en.json
Labels: T-Enhancement, A-Upstream-OAuth, A-Configuration

#2138 Fix the login template in case no human_name was set on the provider
  crates/handlers/src/views/login.rs
  templates/pages/login.html
Labels: T-Defect, A-Login-Flow

#2120 Fix i18next-parser not correctly working on TSX files
  frontend/i18next-parser.config.ts
Labels: T-Task

#2146 Allow `config generate` to generate to a file directly instead of stdout
  crates/cli/src/commands/config.rs
Labels: A-Configuration, A-CLI

#2145 Bump Rust dependencies
  Cargo.lock
  Cargo.toml
  crates/axum-utils/Cargo.toml
  crates/cli/Cargo.toml
  crates/config/Cargo.toml
  crates/email/Cargo.toml
  crates/graphql/Cargo.toml
  crates/handlers/Cargo.toml
  crates/http/Cargo.toml
  crates/i18n/Cargo.toml
  crates/iana-codegen/Cargo.toml
  crates/jose/Cargo.toml
  crates/keystore/Cargo.toml
  crates/listener/Cargo.toml
  crates/oauth2-types/Cargo.toml
  crates/oidc-client/Cargo.toml
  crates/policy/Cargo.toml
  crates/storage-pg/Cargo.toml
  crates/storage/Cargo.toml
  crates/tasks/Cargo.toml
  deny.toml
Labels: A-Dependencies, Z-Deps-Backend
