Repository matrix-org/matrix-authentication-service, pull requests merged in 2024-03, with the labels that each got.

#2439 Update session details styles to closer match latest Figma
  frontend/locales/en.json
  frontend/src/components/Block/Block.module.css
  frontend/src/components/Block/Block.test.tsx
  frontend/src/components/Block/Block.tsx
  frontend/src/components/BlockList/BlockList.module.css
  frontend/src/components/BlockList/BlockList.test.tsx
  frontend/src/components/Client/OAuth2ClientDetail.tsx
  frontend/src/components/Client/__snapshots__/OAuth2ClientDetail.test.tsx.snap
  frontend/src/components/Session/LastActive.tsx
  frontend/src/components/SessionDetail/BrowserSessionDetail.tsx
  frontend/src/components/SessionDetail/CompatSessionDetail.tsx
  frontend/src/components/SessionDetail/OAuth2SessionDetail.tsx
  frontend/src/components/SessionDetail/SessionDetails.module.css
  frontend/src/components/SessionDetail/SessionDetails.tsx
  frontend/src/components/SessionDetail/SessionHeader.module.css
  frontend/src/components/SessionDetail/SessionHeader.tsx
  frontend/src/components/SessionDetail/__snapshots__/CompatSessionDetail.test.tsx.snap
  frontend/src/components/SessionDetail/__snapshots__/OAuth2SessionDetail.test.tsx.snap
  frontend/src/components/SessionDetail/__snapshots__/SessionHeader.test.tsx.snap
  templates/components/scope.html
  translations/en.json
Labels: T-Enhancement

#2455 Make the `mas-cli manage verify-email` mark the email as primary
  crates/cli/src/commands/manage.rs
Labels: A-CLI

#2478 Render browser icon for compat & browser sessions
  crates/spa/src/vite.rs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/BrowserSession.tsx
  frontend/src/components/CompatSession.tsx
Labels: T-Enhancement

#2492 frontend: upgrade @tanstack/react-router
  .github/dependabot.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ButtonLink.tsx
  frontend/src/components/Link.tsx
  frontend/src/components/SessionCard/SessionCard.tsx
  frontend/src/components/UserSessionsOverview/BrowserSessionsOverview.tsx
  frontend/src/components/UserSessionsOverview/__snapshots__/BrowserSessionsOverview.test.tsx.snap
  frontend/src/components/__snapshots__/CompatSession.test.tsx.snap
  frontend/src/components/__snapshots__/OAuth2Session.test.tsx.snap
  frontend/src/routes/__root.tsx
  frontend/src/routes/_account.sessions.$id.tsx
  frontend/src/routes/_account.sessions.browsers.tsx
  frontend/src/routes/_account.sessions.index.tsx
  frontend/src/routes/devices.$id.tsx
Labels: A-Dependencies, Z-Deps-Frontend, A-Frontend

#2506 dependabot: Include storybook-react-i18next in the storybook group
  .github/dependabot.yml
Labels: A-Dependencies, T-Task

#2517 Moved some dependencies in the workspace and upgrade some dependencies
  Cargo.lock
  Cargo.toml
  crates/axum-utils/Cargo.toml
  crates/cli/Cargo.toml
  crates/config/Cargo.toml
  crates/email/Cargo.toml
  crates/graphql/Cargo.toml
  crates/handlers/Cargo.toml
  crates/http/Cargo.toml
  crates/i18n-scan/Cargo.toml
  crates/i18n/Cargo.toml
  crates/iana-codegen/Cargo.toml
  crates/jose/Cargo.toml
  crates/keystore/Cargo.toml
  crates/keystore/tests/keystore.rs
  crates/listener/Cargo.toml
  crates/listener/src/server.rs
  crates/matrix/Cargo.toml
  crates/oidc-client/Cargo.toml
  crates/policy/Cargo.toml
  crates/storage-pg/Cargo.toml
  crates/tasks/Cargo.toml
  crates/templates/Cargo.toml
  crates/tower/Cargo.toml
  deny.toml
Labels: A-Dependencies, Z-Deps-Backend

#2540 ci: build binaries using glibc instead of musl
  .github/workflows/build.yaml
Labels: A-CI
